### https://github.com/alacritty/alacritty/blob/master/alacritty.yml

window:
  startup_mode: Fullscreen

selection:
  # When true, selected text will be copied to the primary clipboard
  save_to_clipboard: true
