# Make background slightly transparent
background_opacity: 0.92

window:
  startup_mode: SimpleFullscreen

selection:
  # When true, selected text will be copied to the primary clipboard
  save_to_clipboard: true
