### https://github.com/alacritty/alacritty/blob/master/alacritty.yml

window:
  startup_mode: Fullscreen

cursor:
  style:
    shape: Beam
    blinking: Always
    vi_mode_style: Beam

selection:
  # When true, selected text will be copied to the primary clipboard
  save_to_clipboard: true

font:
  # Normal (roman) font face
  normal:
    family: Hack Nerd Font
    style: Regular

  # Bold font face
  bold:
    family: Hack Nerd Font
    style: Bold

  # Italic font face
  italic:
    family: Hack Nerd Font
    style: Italic

  # Bold italic font face
  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic
