# https://homebrew-file.readthedocs.io/en/latest/getting_started.html

### Brew
brew alacritty
brew bat
brew exa
brew fd
brew ffmpeg
brew figlet
brew fzf
brew git-delta
brew neofetch
brew neovim
brew ripgrep
brew shellcheck
brew starship
brew swiftlint
brew tmux
brew tokei

### Cask
tap homebrew/cask-fonts
cask font-hack-nerd-font

tap peripheryapp/periphery
cask periphery
