# https://homebrew-file.readthedocs.io/en/latest/getting_started.html

### Brew
brew alacritty
brew bat
brew exa
brew fd
brew figlet
brew git-delta
brew mas
brew neovim
brew ripgrep
brew shellcheck
brew starship
brew swiftlint
brew tmux
brew tokei

### Cask
cask periphery
tap homebrew/cask-fonts
cask font-hack-nerd-font

### AppStore
appstore 1575220747  Bakery       (2.10)
appstore 1091189122  Bear         (1.8.5)
appstore 497799835   Xcode        (13.0)

### Extras
# Postman
# Proxyman
# SF Symbols
